### PR TITLE
reversed comparison logic of length check within RedstoneAware:getOutput() 

### LINKED ISSUE #3439: Redstone output not working
After switching to the latest development build ([`OpenComputers-MC1.10.2-1.7.5.259.jar`](https://ci.cil.li/job/OpenComputers-MC1.10/lastSuccessfulBuild/artifact/build/libs/OpenComputers-MC1.10.2-1.7.5.259-api.jar)), I noticed that redstone output seems not to work anymore. On a computer, after calling `component.redstone.setOutput(sides.front, 15)`, `component.redstone.getOutput(sides.front)` returns 15, but no redstone signal is emitted. If I load the following program onto a microcontroller and turn it on, no signal is output on any side:

    local rs = component.proxy(component.list('redstone')())
    
    for side = 0, 5 do
        rs.setOutput(side, 15)
    end
    
    while true do
        computer.pullSignal(1)
    end

In the latest release, however (`OpenComputers-MC1.12.2-1.7.5.192.jar`), signals are produced in both these experiments.

### PR DESCRIPTION
**Pull request by SanAndreaP**
fixes #3439

### CODE REVIEW

**Comment by v1993** [comment]
Can we *please* get this one merged? Broken redstone is a huge problem.

**Comment by Ocawesome101** [comment]
Seconded.

**Comment by CaitlynMainer** [comment]
@Vexatos Are you able to merge PRs?  If not @fnuecke / @payonel if I could drag one of you out of retirement to assign someone permissions to be able to review and merge PRs that'd be appreciated! <3

File: src/main/scala/li/cil/oc/common/tileentity/traits/RedstoneAware.scala [hunk 1]
```diff
@@ -80,7 +80,7 @@ trait RedstoneAware extends RotationAware {
 
   def getOutput: Array[Int] = EnumFacing.values.map{ side: EnumFacing => _output(toLocal(side).ordinal) }
 
-  def getOutput(side: EnumFacing) = if (_output != null && _output.length <= toLocal(side).ordinal())
+  def getOutput(side: EnumFacing) = if (_output != null && _output.length >= toLocal(side).ordinal())
```
Comment (fnuecke) [inline src/main/scala/li/cil/oc/common/tileentity/traits/RedstoneAware.scala]: Shouldn't this be `_output.length > toLocal(side).ordinal()` then?
Since `toLocal(side).ordinal()` is used as the index, so if it's `== _output.length` it'd be out of bounds?

Comment (SanAndreaP) [reply src/main/scala/li/cil/oc/common/tileentity/traits/RedstoneAware.scala]: Yes, you're right.

**Comment by fnuecke** [comment]
Thanks for the fix :)
